- name:  Configure persistent loading of modules
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Load at runtime overlay and br_netfilter
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: 
    - overlay
    - br_netfilter

- name: Ensure sysctl params are set
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Reload sysctl config
  command: sysctl --system
  