---
- name: Ensure user account is present
  ansible.builtin.user:
    name: "{{ ssh_user.name }}"
    state: "present"
  when:
    - "ssh_user.name | default('')"
    - "ssh_user.name | length > 0"
    - "ssh_user.create_user_account | default(false) | bool"
  loop: "{{ ssh_user_list }}"
  loop_control:
    loop_var: "ssh_user"

- name: Add SSH key to authorized keys
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    dest: "/home/{{ ssh_user.name }}/.ssh/"
    owner: "{{ ssh_user.name }}"
    mode: "0600"
  when: ssh_user.name is defined
       and ssh_user.authorized_keys is not defined
  
- name: Manage authorized ssh keys
  ansible.posix.authorized_key:
    user: "{{ ssh_user.name }}"
    key: "{{ ssh_user.authorized_keys | default([]) | join('\n') }}"
    exclusive: "{{ ssh_authorized_keys_exclusive }}"
  when:
    - ssh_user.name | default('')
    - ssh_user.name | length > 0
  loop: "{{ ssh_user_list }}"
  loop_control:
    loop_var: ssh_user